[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_remappings = false
chain_id = 8453
auto_detect_solc = false
solc_version = "0.8.26"
evm_version = "cancun"
via_ir = false
cbor_metadata = true
use_literal_content = false
bytecode_hash = "none"
optimizer = true
optimizer_runs = 1000
libraries = []

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
